name: Build and deploy Node.js app to Azure Web App - TJweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'ec1de8b0-4d45-418d-b057-840f2824de04'  # Your Client ID
          tenant-id: '1a6baf42-2f45-4410-87b7-599417a8df39'  # Your Tenant ID
          client-secret: 'ygR8Q~mSdXuGeQNfQOoirUHHq92fRMGNHraIna3I'  # Replace with your actual Client Secret
          subscription-id: '59d8d7b9-5130-4a1f-99cf-e43223b08cf8'  # Your Subscription ID

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TJweb'
          slot-name: 'Production'
          package: .
